<a href="https://colab.research.google.com/github/keerthanadevisaminathan/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l=[1,2,3]
l.append(4)
print(l)

[1, 2, 3, 4]


In [ ]:
t=(1,2,3)
tuple=t+(4,)
print(tuple)

(1, 2, 3, 4)


In [ ]:
d={'x':1,'y':1}
print(d)
d['z']=1
print(d)

{'x': 1, 'y': 1}
{'x': 1, 'y': 1, 'z': 1}


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [ ]:
import numpy as np
a=np.array([[1,2],[2,2],[2,3]])
print(a.shape)

(3, 2)


In [ ]:
a=np.arange(5,16,2)
print(a)

[ 5  7  9 11 13 15]


In [ ]:
a=np.array([1,2],dtype='float')
print(a)

[1. 2.]


In [ ]:
a=np.random.random(3)
print(a)

[0.45361761 0.49624991 0.42119194]


In [ ]:
a=np.random.random([2,3])
print(a)

[[0.95633694 0.76803255 0.68255872]
 [0.70617705 0.03590675 0.38465126]]


In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones([1,2])

array([[1., 1.]])

In [ ]:
np.random.random((4,3,2))

array([[[0.11114397, 0.45015644],
        [0.3882654 , 0.31382375],
        [0.26754548, 0.07980845]],

       [[0.21829587, 0.0405505 ],
        [0.89956258, 0.64271523],
        [0.55961681, 0.22129481]],

       [[0.027652  , 0.46123041],
        [0.00492706, 0.3685298 ],
        [0.97969112, 0.21722066]],

       [[0.92554988, 0.95920951],
        [0.05419017, 0.56562522],
        [0.32552174, 0.22808656]]])

In [ ]:
a=np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


In [ ]:
a=np.eye(2,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
a=np.linspace(0,1,num=5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a=np.array([[1,2],[2,3],[3,4]])
print(a[0:2])

[[1 2]
 [2 3]]


In [ ]:
a=np.array([[1,2],[2,3],[3,4]])
print(a[0:3:2])

[[1 2]
 [3 4]]


In [ ]:
a=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
print(a[0:2,1:3])

[[2 3]
 [3 4]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[1,:])
print(a[1:3,3])
print(a[1:3,1:3])
print(a[:,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 8 12]
[[ 6  7]
 [10 11]]
[ 2  6 10]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,24,35,16]])
b=np.array([0,1,2])
print(a[np.arange(3),b])

[ 1  6 11]


In [ ]:
a=np.array([4,36,839,33])
print(np.argmax(a))

2


In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 24, 35, 16]])
max_index = np.argmax(a)
print(max_index)


14


In [ ]:
import numpy as np
a=np.array([[1,2,10],[4,5,6],[7,8,9]])
flat=np.argmax(a)
print(np.unravel_index(flat,a.shape))

(0, 2)


In [ ]:
import numpy as np
a=np.array([[1,2],[4,5]])
b=np.array([[11,12,13],[14,15,16]])
r=a@b
print(r)

[[ 39  42  45]
 [114 123 132]]


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([1,2,3])

result = a @ b

print(result)


14


In [ ]:
import numpy as np
a=np.array([[1,2],[4,5]])
b=np.array([[11,12,13],[14,15,16]])
print(np.dot(a,b))

[[ 39  42  45]
 [114 123 132]]


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(np.reshape(a,(2,2)))

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=10
c=a+b
print(c)

[11 12 13 14 15]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
c=a+b
print(c)

[ 2  4  6  8 10]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
b=np.array([1,2,3,4,5])
c=a+b
print(c)

[[ 2  4  6  8 10]
 [ 7  9 11 13  5]]
